
<h1 class="history">A propos de nous</h1>
<article class="equipe container">
	<div>
		<h2 class="title">Notre équipe</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, facere, voluptate, unde aliquid delectus ratione consectetur omnis quam sapiente aspernatur modi ipsam veniam recusandae est a tempore velit inventore veritatis?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, facere, voluptate, unde aliquid delectus ratione consectetur omnis quam sapiente aspernatur modi ipsam veniam recusandae est a tempore velit inventore veritatis?</p>
	</div>
	<div class="imgEquipe">
		<img src="img/chef.jpg" alt="equipe" class="height"></img>
		<img src="img/chef2.jpg" alt="equipe"></img>
	</div>
</article>

<section class="container">
	<h2 class="title">Notre concept</h2>
	<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident, voluptate maiores  </p>
<div class="concept">
					<ul>
						<li>
							<i class="fa-regular fa-face-smile"></i>
							<h3>Service rapide</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae.</p>
						</li>
							<li>
							<i class="fa-solid fa-spoon"></i>
							<h3>Dejeuner</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae.</p>
						</li>
						<li>
							<i class="fa-regular fa-gem"></i>
							<h3>Nourriture délicieuse</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae. </p>
						</li>
						<li>
							<i class="fa-solid fa-bread-slice"></i>
								<h3>Petit déjeuner</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae. </p>
						</li>
						<li>
								<i class="fa-sharp fa-regular fa-thumbs-up"></i>
								<h3>Dessert</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae. </p>
						</li>
						
						
						<li>
							<i class="fa-solid fa-utensils"></i>
							<h3>Dinner</h3>
							<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur tempore sed doloribus animi consectetur at ducimus molestias fuga eum molestiae. </p>
						</li>
						


					</ul>
				</div>
</section>

<section>
	<h2 class="title">Lorem ipsum dolor </h2>
	<article>
		<p class="p-about">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, totam.</p>
		<video controls poster="medias/poster.png">
			<source src="medias/cooking.mp4" type="video/mp4">
		</video>
	</article>
</section>

