
  	<section class="formdesing">
   <div class="wrapperM ">
       
        <div class="containerForm">
            <div class="col-left">
                
            </div>
            <div class="col-right">
                <div class="login-form">
                    <h2>Mot de passe oublié</h2>
                    <form action="" method="POST">
                        <p>
                            <label>E-mail<span>*</span></label>
                            <input type="email" name="email" id="email" placeholder="Email" value="<?= $email ?>">
                             <span class="error"> <?=  $errors['email'] ?? '';?></span>
                        </p>
                     
                        <p>
                            <input type="submit" value="Réinitialiser">
                        </p>
  
                    </form>
                   <span class="error"><?= $errors['message'] ?? '';?></span>
                </div>
               <a href="registration.php" class="">Pas de compte ? Créez-en un ici</a> 
            </div>
                 
        </div>
        
    </div>
    </section>

    