<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
   <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="css/style.css">
	<title>Password</title>

</head>

<body>

<header>

    <nav class="navbar container">

        <a class="navbar-brand" href="#">

        <img src="img/Logo-restaurant.PNG" alt="Logo restaurant">

        </a>
    </nav>

</header>
   <main>

        <section>

        <h1 class="text-center">Réinitialiser votre mot de passe</h1>  

</section>
    <div class="container">        

    <div class="row">

        <div class="col-md-6 offset-md-3 pt-3">

        <form  action="" method="post">

    <div class="form-group mb-3">

            <label for="newPassword" class="mb-2" id="labelPassword">Nouveau mot de passe</label>

            <input name="newPassword" type="password" class="form-control"/>

    </div>

    <div class="form-group mb-3">

            <label for="newPassword" class="mb-2" id="labelConfirm">Confirmation de votre nouveau mot de passe</label>

            <input id="txtConPassword" type="Password" class="form-control"

            name="confirmPassword">
    </div>

     <div class=" flexBtn">
    <button

    type="submit"

    class=" mt-4 " name="confirm">

    Confirmer

    </button>

    </div>

    <div class="text-center text-danger mt-4" id="message"> 
    <!--<?= $message; ?> </div>-->

</form>

</div>

</div>

</main>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<script src="js/langue.js"></script>

 

</body>

</html>