<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<head>
	<meta charset="UTF-8">
	 <meta name="description" content="La Malvasia Restaurant, your new favourite restaurant !">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="img/icon.png" type="image/x-png" />
	<title>La Malvasia Restaurant</title>
	
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
	<link rel="stylesheet" type="text/css" href="css/slick.css" />
	<link rel="stylesheet" type="text/css" href="css/slick-theme.css" />
	<link href="css/nouislider.min.css" rel="stylesheet"/>
	<link rel="stylesheet" href="css/style.css"/>
</head>

<body>
		<header>

		<nav class="navbar">
			<ul class="navbarUl">
				
				<li class="first"><a href="index.php" class="active">Accueil</a></li>
				<li class="second"><a href="about.php">A propos de nous</a></li>
				<li class="third"><a href="product.php">Nos Produits</a></li>
				<li class="four"><a href="#contact">Contact</a></li>
				<?php if(Session::isConnected() && $_SESSION['login']['role']): ?>
						<li class="fifth"><a href="addProduct.php">ajouter</a></li>
						<?php endif ; ?>

			</ul>
			<div class="flex">
				<a href="index.php">
						<img src="img/Logo-restaurant.PNG" alt="Logo de restaurant">
				</a>
				 <form  action="apiSearch.php">
			      <input  placeholder="Recherche" name="q" id="search" aria-label="Search" list="searchList">
			      <datalist id="searchList">
			        </datalist> 
			    </form>
				<?php 
    				if(Session::isConnected()): ?>
					
					<a href="logout.php"><i class="fa-solid fa-right-to-bracket"></i></a>
					<?php 
    			else: ?>

					<a href="authentification.php" ><i class="fa-solid fa-circle-user"></i></a>
					<?php endif ; ?>
					<a href="cart.php"class="badge" ><i class="fa-sharp fa-solid fa-cart-shopping"></i>
					<span  id="number"></span></a>
			</div>	
			<div class="menuBtn" id="hamburger">
				<div class="bar1"></div>
				<div class="bar2"></div>
				<div class="bar3"></div>
			</div>
		
		</nav>
	</header>
	<main>
		<?= $pageContent ?>
	</main>
	
    <footer>
        <aside class="footer-1 container">
          	<a href="index.php">
						<img src="img/Logo-restaurant.PNG" alt="Logo de restaurant">
					</a>
           <p class="p-footer">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe qui repellat nam vero consectetur dicta eos suscipit. Numquam at minus architecto asperiores cupiditate. At molestias laborum voluptatibus numquam aperiam in. </p>
        </aside>
        <div class="flex-footer container">
        <aside>
            <span>Address</span>
            <address>
                   <p> <i class="fa-sharp fa-solid fa-location-dot"></i>&nbsp;Lorem ipsum, dolor sit amet consectetur adipisicing elit</p>
                    <p>Saepe qui repellat</p>
            </address>

        </aside>
         <aside id="contact">
            <span>Contact Us</span>
            <address>
                    <p><i class="fa-solid fa-phone"></i>&nbsp;+(21)-255-999-8888 </p>
                    <p><i class="fa-solid fa-envelope"></i>&nbsp;lorem@lorem.com</p>
            </address>

        </aside>

        <aside>
            <span>Social networks</span>
            <div class="social">
                <a href="#" class="fab fa-facebook-f"></a>
                <a href="#" class="fab fa-instagram"></a>
                <a href="#" class="fab fa-pinterest-p"></a>
            </div>
		</aside>
		<aside>
			<span>Feedback</span>
			<a href="feedback.php" class="p-fee">Votre avis nous interesse</a>
		</aside>


    </div>
    </footer>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script type="text/javascript" src="js/carousel.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="js/dropdown.js"></script>
	<script type="module" src="js/localStorage/localStorage.js"></script>
	<script type="module" src="js/localStorage/displayCart.js"></script>
	<script type="module" src="js/fetch.js"></script>
	<script type="module" src="js/localStorage/storage.js"></script>
	<script type="module" src="js/localStorage/events.js"></script>
	<script type="module" src="js/localStorage/remove.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="module" src="js/scripts_paiement.js"></script>
    <script type="module" src="js/status.js"></script>
    <script src="js/mixitup.min.js"></script>
	<script type="text/javascript" src="js/mix.js"></script>
	<script type="text/javascript" src="js/slick.min.js" defer></script>
    <script type="text/javascript" src="js/slick.js" defer></script>
     <script src="js/nouislider.js" defer></script>
     <script src="js/slider.js" defer></script>
      <script src="js/search.js" defer></script>
</body>

</html>
