
<!--mise à jour de prix-->
<section class="container">
    <form action="" method="POST">
     	<fieldset>
		    <legend>Modifier le prix du produit</legend>
    
    <div class="field">
        <label for="price">Nouveau prix</label>
       	<div class="value"> <input type="text" id="price" name="price" class="inputPrice"> </div>
    </div>

        <button type="submit" class="button-menu">Enregistrer</button>
    </fieldset>
    </form>
</section>